services:
  web-opm:
    build:
      context: ..
      dockerfile: Dockerfile
    image: hylkevds/frost-http-observableproperties:latest
    ports:
      - 8080:8080
    depends_on:
      database-opm:
        condition: service_healthy
      mosquitto-opm:
        condition: service_started
    environment:
      - serviceRootUrl=http://localhost:8080/FROST-Server
      - queueLoggingInterval=1000
      - http_cors_enable=true
      - http_cors_allowed_origins=*
      - bus_mqttBroker=tcp://mosquitto-opm:1883
      - bus_sendQueueSize=2000
      - bus_sendWorkerPoolSize=10
      - bus_maxInFlight=2000
      - persistence_db_driver=org.postgresql.Driver
      - persistence_db_url=jdbc:postgresql://database-opm:5432/sensorthings
      - persistence_db_username=sensorthings
      - persistence_db_password=ChangeMe
      - persistence_autoUpdateDatabase=true

  mosquitto-opm:
    image: eclipse-mosquitto
    volumes:
      - "./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro"

  database-opm:
    image: postgis/postgis:16-3.4-alpine
    environment:
      - POSTGRES_DB=sensorthings
      - POSTGRES_USER=sensorthings
      - POSTGRES_PASSWORD=ChangeMe
    volumes:
      - postgis_volume-opm:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d sensorthings -U sensorthings "]
      interval: 2s
      timeout: 2s
      retries: 10

volumes:
    postgis_volume-opm:
