version: '3'

services:
  web:
    image: hylkevds/frost-http-observableproperties:latest
    ports:
      - 8080:8080
    depends_on:
      - database
      - mosquitto
    environment:
      - serviceRootUrl=http://localhost:8080/FROST-Server
      - queueLoggingInterval=1000
      - http_cors_enable=true
      - http_cors_allowed_origins=*
      - bus_mqttBroker=tcp://mosquitto:1883
      - bus_sendQueueSize=2000
      - bus_sendWorkerPoolSize=10
      - bus_maxInFlight=2000
      - persistence_db_driver=org.postgresql.Driver
      - persistence_db_url=jdbc:postgresql://database:5432/sensorthings
      - persistence_db_username=sensorthings
      - persistence_db_password=ChangeMe
      - persistence_autoUpdateDatabase=true

  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - "./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro"

  database:
    image: postgis/postgis:11-2.5-alpine
    environment:
      - POSTGRES_DB=sensorthings
      - POSTGRES_USER=sensorthings
      - POSTGRES_PASSWORD=ChangeMe
    volumes:
      - postgis_volume:/var/lib/postgresql/data

volumes:
    postgis_volume:
